version: "2"
services:
  home:
    build: .
    image: sifut/home
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html

  blog:
    build: blog
    image: sifut/blog
    ports:
      - "3001:2368"
    volumes:
      - ./blog:/var/lib/ghost/content
