compass:
    image: stevevega/compass
    command: watch --poll
    volumes:
        - ./compass:/input
        - ./public/css:/output
go:
    build: .
    volumes:
        - ./public:/go/src/app/public
        - ./view:/go/src/app/view
ghost:
    image: ghost:latest
    environment:
        NODE_ENV: development
    volumes:
        - ./ghost/config.js:/var/lib/ghost/config.js
        - ~/docker/volumes/sinfut/data/ghost:/var/lib/ghost
nginx:
    image: nginx:latest
    links:
        - go
        - ghost
    ports:
        - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/vhost:/etc/nginx/conf.d:ro